version: '3.8'

services:
  backend:
    build: ./Node-backend
    ports:
      - "5000:5000"
    container_name: node-backend

  frontend:
    build: ./React-front
    ports:
      - "80:80"
    container_name: react-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000

