name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ci-cd-demo || git clone https://github.com/Saipriyakapuganti/ci-cd-demo.git && cd ci-cd-demo
            git pull origin main
            docker compose down --volumes --remove-orphans || true
            docker compose build --no-cache
            docker compose up -d

